### ISSUE TITLE
Cmake errors when building with the Dawn backend

### ISSUE THREAD

**Issue by bobajeff** [eliemichel/WebGPU-distribution#1]
I'm trying to use the Dawn backend in my project. However when running `cmake -B build` I get a serious of errors which seem to indicate missing directories.

### output:

```bash
-- Dawn: using SPIRV-Headers at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/vulkan-deps/spirv-headers/src
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:23 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/vulkan-deps/spirv-headers/src"
  which is not an existing directory.


-- Dawn: using SPIRV-Tools at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/vulkan-deps/spirv-tools/src
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:48 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/vulkan-deps/spirv-tools/src"
  which is not an existing directory.


-- Dawn: using Abseil at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/abseil-cpp
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:67 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/abseil-cpp"
  which is not an existing directory.


-- Dawn: using Vulkan-Headers at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/vulkan-deps/vulkan-headers/src
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:72 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/vulkan-deps/vulkan-headers/src"
  which is not an existing directory.


-- Found PythonInterp: /usr/bin/python3 (found version "3.10.6") 
-- Dawn: using python at /usr/bin/python3
-- Dawn: using jinja2 at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/jinja2
Traceback (most recent call last):
  File "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/generator/dawn_version_generator.py", line 18, in <module>
    from generator_lib import Generator, run_generator, FileRender
  File "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/generator/generator_lib.py", line 94, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
CMake Error at build/_deps/dawn-src/generator/CMakeLists.txt:65 (message):
  Dawn: Failed to get the dependencies for Dawn version based utilities.
  Base args are
  '/usr/bin/python3;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/generator/dawn_version_generator.py;--template-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/generator/templates;--root-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src;--output-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-build/gen;--dawn-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src;--jinja2-path;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/_deps/dawn-src/third_party/jinja2'.
Call Stack (most recent call first):
  build/_deps/dawn-src/src/dawn/common/CMakeLists.txt:15 (DawnGenerator)


-- Configuring incomplete, errors occurred!
See also "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn/build/CMakeFiles/CMakeOutput.log".

```

### things I've checked:
I've also tried building the upstream [Dawn project](https://dawn.googlesource.com/dawn/+/HEAD/docs/building.md) and it builds and runs demo code successfully. That's as far as my cmake knowledge will take me however.

**Comment by eliemichel** [comment]
Are these the very first line of CMake's output? It seems that the dependencies are not cloned.

The upstream Dawn projects requires the installation of an extra tool (`depot_tools`) to handle this, but it is overkill so I replaced it with [this script](https://github.com/eliemichel/WebGPU-distribution/blob/dawn/tools/fetch_dawn_dependencies.py) but apparently in your case it did not run. Maybe the beginning of the log can hint why (you have Python installed, right? Upstream Dawn requires it too anyways).

Whatever the problem is with this script, the error message should indeed be more informative, let me know the extra log and I'll work on it!

**Comment by bobajeff** [comment]
@eliemichel
No sorry. This is the full output:

```bash
cmake -B build
-- The CXX compiler identification is GNU 11.3.0
-- The C compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Using X11 for window creation
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Using Dawn backend for WebGPU
-- fetch_dawn_dependencies: 
-- No build type selected, default to Debug
-- Dawn build D3D12 backend: OFF
-- Dawn build Metal backend: OFF
-- Dawn build Vulkan backend: ON
-- Dawn build OpenGL backend: OFF
-- Dawn build OpenGL ES backend: OFF
-- Dawn build Null backend: OFF
-- Dawn build with asserts in all configurations: OFF
-- Dawn build Wayland support: OFF
-- Dawn build X11 support: ON
-- Dawn build samples: OFF
-- Dawn build Node bindings: OFF
-- Dawn build Swiftshader: OFF
-- Dawn build PIC: OFF
-- Dawn build with ASAN: OFF
-- Dawn build with TSAN: OFF
-- Dawn build with MSAN: OFF
-- Dawn build with UBSAN: OFF
-- Tint build samples: OFF
-- Tint build docs: OFF
-- Tint build docs with warn as error: OFF
-- Tint build SPIR-V reader: OFF
-- Tint build WGSL reader: ON
-- Tint build GLSL writer: OFF
-- Tint build HLSL writer: OFF
-- Tint build MSL writer: OFF
-- Tint build SPIR-V writer: ON
-- Tint build WGSL writer: ON
-- Tint build IR: ON
-- Tint build fuzzers: OFF
-- Tint build SPIRV-Tools fuzzer: OFF
-- Tint build AST fuzzer: OFF
-- Tint build regex fuzzer: OFF
-- Tint build benchmarks: OFF
-- Tint build tests: OFF
-- Tint build checking [chromium-style]: OFF
-- Tint build remote-compile tool: OFF
-- Using python3
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.6", minimum required is "3") 
-- Dawn: using SPIRV-Headers at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/vulkan-deps/spirv-headers/src
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:23 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/vulkan-deps/spirv-headers/src"
  which is not an existing directory.


-- Dawn: using SPIRV-Tools at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/vulkan-deps/spirv-tools/src
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:48 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/vulkan-deps/spirv-tools/src"
  which is not an existing directory.


-- Dawn: using Abseil at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/abseil-cpp
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:67 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/abseil-cpp"
  which is not an existing directory.


-- Dawn: using Vulkan-Headers at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/vulkan-deps/vulkan-headers/src
CMake Error at build/_deps/dawn-src/third_party/CMakeLists.txt:72 (add_subdirectory):
  add_subdirectory given source
  "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/vulkan-deps/vulkan-headers/src"
  which is not an existing directory.


-- Found PythonInterp: /usr/bin/python3 (found version "3.10.6") 
-- Dawn: using python at /usr/bin/python3
-- Dawn: using jinja2 at /home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/jinja2
Traceback (most recent call last):
  File "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/generator/dawn_version_generator.py", line 18, in <module>
    from generator_lib import Generator, run_generator, FileRender
  File "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/generator/generator_lib.py", line 94, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
CMake Error at build/_deps/dawn-src/generator/CMakeLists.txt:65 (message):
  Dawn: Failed to get the dependencies for Dawn version based utilities.
  Base args are
  '/usr/bin/python3;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/generator/dawn_version_generator.py;--template-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/generator/templates;--root-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src;--output-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-build/gen;--dawn-dir;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src;--jinja2-path;/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/_deps/dawn-src/third_party/jinja2'.
Call Stack (most recent call first):
  build/_deps/dawn-src/src/dawn/common/CMakeLists.txt:15 (DawnGenerator)


-- Configuring incomplete, errors occurred!
See also "/home/bobajeff/projects/webgpu_native_exp/LearnWebGPU_Dawn_bug_report/build/CMakeFiles/CMakeOutput.log".

```

**Comment by bobajeff** [comment]
For what it's worth I managed to get the upstream Dawn to work with the guide by [manually fetching it](https://dawn.googlesource.com/dawn/+/HEAD/docs/building.md#get-the-code) adding it as a sub-directory in my project and linking in `webgpu_dawn` instead of `webpgu` in my project.

[workingproject.zip](https://github.com/eliemichel/WebGPU-distribution/files/11234657/workingproject.zip)

**Comment by eliemichel** [comment]
Thanks for the details! I just updated the `dawn` branch to better find Python when fetching dependencies, could you try again from a fresh clone?

**Comment by bobajeff** [comment]
Thanks! It's working now.

**Comment by eliemichel** [comment]
Great thanks for your feedback!
